package usecase.purchase

import domain.model.Item

/**
 * The response generated by the [PurchaseUseCase] execution.
 *
 * @author Nicola Lasagni on 11/08/2021.
 */
data class PurchaseResponse(
    val items: Collection<Item>,
    val salesTaxesAmount: Float,
    val totalPrice: Float
)
