package usecase.purchase

import domain.model.Receipt

/**
 * The response generated by the [PurchaseUseCase] execution.
 *
 * @author Nicola Lasagni on 11/08/2021.
 */
data class PurchaseResponse(val receipt: Receipt)
