package usecase.addtobasket

import domain.model.ProductInBasket

/**
 * The response generated by the [AddToBasketUseCase] execution.
 *
 * @author Nicola Lasagni on 11/08/2021.
 */
data class AddToBasketResponse(val productInBasket: ProductInBasket)
